version: 1.0.{build}
environment:
  matrix:
  - job_name: Documentation
    job_group: Build
    appveyor_build_worker_image: Ubuntu
  
  - job_name: libffi-ARM64
    appveyor_build_worker_image: Visual Studio 2019
  
  - job_name: Build x64
    job_group: Build
    appveyor_build_worker_image: Visual Studio 2019
  
  - job_name: Build ARM64
    job_group: Build
    job_depends_on: libffi-ARM64
    appveyor_build_worker_image: Visual Studio 2019
    
  - job_name: Package
    job_depends_on: Build
    appveyor_build_worker_image: Visual Studio 2019
    pcbuild\build.bat -p ARM64 --no-tkinter
